<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AuthorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuthorRepository extends EntityRepository
{
    public function findAuthorWithDependencies($slug)
    {
        return $this->createQueryBuilder('a')
            ->select('a, p, t, c')
            ->join('a.posts', 'p')
            ->join('p.tags', 't')
            ->leftJoin('p.comments', 'c')
            ->where('a.slug = :slug')
            ->setParameter('slug', $slug)
            ->orderBy('p.createdAt', 'DESC')
            ->getQuery()
            ->getOneOrNullResult();
    }
}
