<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
    public function findLastComments($number = 5)
    {
        return $this->createQueryBuilder('c')
            ->select('c, p')
            ->join('c.post', 'p')
            ->orderBy('c.createdAt', 'DESC')
            ->getQuery()
            ->setMaxResults($number)
            ->getResult();
    }

    public function findCommentsByPost($slug)
    {
        return $this->createQueryBuilder('c')
            ->select('c, p')
            ->join('c.post', 'p')
            ->where('p.slug =:slug')
            ->setParameter('slug', $slug)
            ->orderBy('c.createdAt', 'DESC')
            ->getQuery()
            ->getResult();
    }
}
