<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * CommentRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
    public function findLastComments($number = 5)
    {
        return $this->createQueryBuilder('c')
            ->select('c, p')
            ->join('c.post', 'p')
            //->join('p.author', 'a')
            //->leftJoin('p.tags', 't')
            ->orderBy('c.createdAt', 'DESC')
            ->getQuery()
            ->setMaxResults($number)
            ->getResult();
    }

    public function findCommentsByPost($slug)
    {
        return $this->createQueryBuilder('c')
            ->select('c, p')
            ->join('c.post', 'p')
            ->where('p.slug =:slug')
            ->setParameter('slug', $slug)
            ->orderBy('c.createdAt', 'DESC')
            ->getQuery()
            ->getResult();
    }

    public function findAllSorted()
    {
        return $this->createQueryBuilder('c')
            ->select('c, p')
            ->join('c.post', 'p')
            ->orderBy('c.createdAt', 'DESC')
            ->getQuery()
            ->getResult();

    }

    public function countAllComments()
    {
        return $this->createQueryBuilder('c')
            ->select('count(c.id)')
            ->getQuery()
            ->getSingleScalarResult();
    }

    public function findAllCommentsWithDependencies($currentPage, $limit)
    {
        $query = $this->createQueryBuilder('c')
            ->select('c, p')
            ->leftJoin('c.post', 'p')
            ->addOrderBy('c.createdAt', 'DESC')
            ->addOrderBy('c.updatedAt', 'DESC')
            ->getQuery()
            ->setFirstResult($limit * ($currentPage -1))
            ->setMaxResults($limit);

        return new Paginator($query);

    }
}
