<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    public function findAllPostsWithDependencies()
    {
        return $this->createQueryBuilder('p')
            ->select('p, a')
            ->leftJoin('p.author', 'a')
            ->orderBy('p.createdAt', 'DESC')
            ->getQuery()
            ->getResult();
    }

    public function findPostBySlug($slug)
    {
        return $this->createQueryBuilder('p')
            ->select('p, a, c')
            ->leftJoin('p.comments', 'c')
            ->leftJoin('p.author', 'a')
            ->where('p.slug = :slug')
            ->setParameter('slug', $slug)
            ->getQuery()
            ->getOneOrNullResult();
    }

    public function findTopPosts($number = 5)
    {
        return $this->createQueryBuilder('p')
            ->select('p, c, a, avg(c.rating) as rating')
            ->leftJoin('p.comments', 'c')
            ->join('p.author', 'a')
            ->groupBy('p, a')
            ->orderBy('rating', 'DESC')
            ->getQuery()
            ->setMaxResults($number)
            ->getResult();
    }
}
