<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TagRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository
{
    public function findAllTagsWithDependencies()
    {
        return $this->createQueryBuilder('t')
            ->select('t, p')
            ->leftJoin('t.posts', 'p')
            ->getQuery()
            ->getResult();
    }

    public function findTagWithPosts($slug)
    {
        return $this->createQueryBuilder('t')
            ->select('t, p')
            ->leftJoin('t.posts', 'p')
            ->where('t.slug = :slug')
            ->setParameter('slug', $slug)
            ->getQuery()
            ->getOneOrNullResult();

    }
}
