<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TagRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository
{
    public function findAllTagsWithCountPosts()
    {
        return $this->createQueryBuilder('t')
            ->select('t, count(p.id) as countPosts')
            ->leftJoin('t.posts', 'p')
            ->orderBy('count(p.id)', 'DESC')
            ->getQuery()
            ->getResult();
    }
}
