<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function findUserWithDependencies($slug)
    {
        return $this->createQueryBuilder('u')
            ->select('u, p, t, c')
            ->join('u.posts', 'p')
            ->join('p.tags', 't')
            ->leftJoin('p.comments', 'c')
            ->where('u.slug = :slug')
            ->setParameter('slug', $slug)
            ->orderBy('p.createdAt', 'DESC')
            ->getQuery()
            ->getOneOrNullResult();
    }

}
