<?php
/**
 * Created by PhpStorm.
 * User: fumus
 * Date: 13.01.16
 * Time: 15:44
 */

namespace AppBundle\Form;


use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CommentType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        //parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
        $builder
            ->add('commentAuthor', TextType::class)
            ->add('text', TextAreatype::class)
            ->add('rating', ChoiceType::class, array(
                'choices' => range(1, 5),
                'choices_as_values' => true,
                'placeholder' => 'Rating'
            ))
        ;

    }

    public function configureOptions(OptionsResolver $resolver)
    {
       // parent::configureOptions($resolver); // TODO: Change the autogenerated stub
        $resolver->setDefaults(
            array(
                'data_class' => 'AppBundle\Entity\Comment',
                'em' => null,
            )
        );
    }
}