<?php
/**
 * Created by PhpStorm.
 * User: fumus
 * Date: 13.01.16
 * Time: 15:44
 */

namespace AppBundle\Form;


use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CommentType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        //parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
        $builder
            //->add('commentAuthor', TextType::class, array('label' => 'Your name'))
            ->add('text', TextAreatype::class, array('label' => 'Comment', 'required' => false, 'translation_domain' => 'messages'))
            ->add(
                'rating',
                NumberType::class,
                [
                    'attr' => [
                        'class' => 'rating',
                        'data-min' => 0,
                        'data-max' => 5,
                        'data-step' => 1,
                        'data-show-clear' => 'false',
                        'data-size' => 'xs',
                        //'data-glyphicon' => false,
                    ],
                    'label' => 'Rate this post',
                    'translation_domain' => 'messages'
                ]
            )
        ;

    }

    public function configureOptions(OptionsResolver $resolver)
    {
        // parent::configureOptions($resolver); // TODO: Change the autogenerated stub
        $resolver->setDefaults(
            array(
                'data_class' => 'AppBundle\Entity\Comment',
                'em' => null,
            )
        );
    }
}